//! Renderer-side description of a gizmo that should be drawn this frame.
//!
//! The structure mirrors a subset of the core `GizmoState` but omits
//! interaction data (dragging, highlighted axis) that the renderer doesn't
//! care about.  Clients call [`Renderer::queue_gizmo`] with one or more
//! instances, and the renderer will bake them into a vertex buffer and draw
//! them using the line pipeline.

use glam::Mat4;

/// A single gizmo to render.  `transform` is the world-space matrix for the
/// handle origin; vertices generated by the renderer will be pre‑multiplied
/// by this matrix before being uploaded to the GPU.
#[derive(Debug, Clone)]
pub struct GizmoDraw {
    pub transform: Mat4,
    pub mode: ferrous_core::scene::GizmoMode,
    /// If the editor has highlighted a particular axis this frame the
    /// renderer can render that axis with a brighter colour.
    pub highlighted_axis: Option<ferrous_core::scene::Axis>,
    /// If the editor has highlighted a plane handle, the renderer brightens it.
    pub highlighted_plane: Option<ferrous_core::scene::Plane>,
    /// Full visual style for this gizmo (colors, sizes, arrows, planes…).
    pub style: ferrous_core::scene::GizmoStyle,
}

impl GizmoDraw {
    pub fn new(transform: Mat4, mode: ferrous_core::scene::GizmoMode) -> Self {
        Self {
            transform,
            mode,
            highlighted_axis: None,
            highlighted_plane: None,
            style: ferrous_core::scene::GizmoStyle::default(),
        }
    }
}
