use crate::constraint::Constraint;
use crate::layout::{Node, RenderCommand};
use crate::GuiKey;

/// Cualquier elemento de la interfaz que pueda "dibujarse".
///
/// En lugar de acoplarse al renderer, la abstracción devuelve una lista de
/// `RenderCommand` genéricos. Más adelante el código que use la UI puede
/// convertirlos a `GuiBatch` y `TextBatch` según corresponda.
pub trait Widget {
    /// collect render commands for this widget (called during draw pass)
    fn collect(&self, cmds: &mut Vec<RenderCommand>);

    /// simple hit test used by focus/navigation; coordinates are in window
    /// space (same as the various `hit` helpers defined on specific widgets).
    /// The default implementation returns `false` which means the widget is
    /// not interactable.
    fn hit(&self, _mx: f64, _my: f64) -> bool {
        false
    }

    /// called when a mouse button changes state (pressed or released). The
    /// coordinates correspond to the event location. Widgets can update their
    /// internal state (hover, pressed, dragging, focus, etc.) here. The
    /// default implementation does nothing.
    fn mouse_input(&mut self, _mx: f64, _my: f64, _pressed: bool) {}

    /// called when the cursor moves. Useful for updating hover or dragging
    /// behaviour. The default implementation does nothing.
    fn mouse_move(&mut self, _mx: f64, _my: f64) {}

    /// keyboard event forwarded to whichever widget currently has focus.
    /// `text` contains any Unicode text generated by the key (e.g. from
    /// `ReceivedCharacter` events) while `key` is an optional keycode that
    /// can be used for handling non-text keys such as backspace. `pressed`
    /// indicates whether the key was pressed (true) or released (false).
    /// The default implementation is a no-op.
    fn keyboard_input(&mut self, _text: Option<&str>, _key: Option<GuiKey>, _pressed: bool) {}

    /// Optional rectangle occupied by the widget in window coordinates.  The
    /// default implementation returns `None`, meaning the container cannot
    /// infer any size from this widget.  Widgets that maintain a `rect`
    /// field (e.g. `Button`, `Slider`, `Node` wrappers) should override
    /// this and return `Some(rect)` so that parent containers can perform
    /// auto-sizing.
    fn bounding_rect(&self) -> Option<[f32; 4]> {
        None
    }

    /// Optional tooltip string for this widget.  When `Some` the calling
    /// application may display it near the cursor while the widget is hovered.
    /// The default implementation returns `None`.
    fn tooltip(&self) -> Option<&str> {
        None
    }

    /// Apply a [`Constraint`] to this widget given the container (or window)
    /// dimensions.  The default implementation is a no-op; widgets that have
    /// a `rect` field and a `constraint` field override this to call
    /// [`Constraint::apply_to_rect`].
    fn apply_constraint(&mut self, _container_w: f32, _container_h: f32) {}

    /// Shift the widget's position by `(dx, dy)` pixels.  The default
    /// implementation uses `bounding_rect` to read the current position and
    /// then calls `apply_constraint` with a `Px` constraint so that
    /// concrete widgets update their internal rect.
    fn shift(&mut self, dx: f32, dy: f32) {
        if let Some(r) = self.bounding_rect() {
            // Apply a pure-Px position override; container sizes are 0 because
            // Px expressions ignore them entirely.
            let c = Constraint::new()
                .x(crate::constraint::SizeExpr::px(r[0] + dx))
                .y(crate::constraint::SizeExpr::px(r[1] + dy));
            // Temporarily hijack apply_constraint with this synthetic constraint.
            // We store + restore the widget's own constraint around the call so
            // we don't clobber it.  Because trait objects can't do that generically,
            // we instead call apply_constraint_with.
            self.apply_constraint_with(&c, 0.0, 0.0);
        }
    }

    /// Apply an *external* constraint (not necessarily the widget's own stored
    /// one) given container dimensions.  The default no-op is fine for widgets
    /// that don't have a rect; concrete widgets override this to update their
    /// position/size.
    fn apply_constraint_with(&mut self, _c: &Constraint, _cw: f32, _ch: f32) {}
}

// make Node itself a widget so containers composed of nodes can be used as widgets
impl Widget for Node {
    fn collect(&self, cmds: &mut Vec<RenderCommand>) {
        self.collect_render_commands(cmds);
    }

    fn bounding_rect(&self) -> Option<[f32; 4]> {
        Some([self.rect.x, self.rect.y, self.rect.width, self.rect.height])
    }
}

// convenience impl so that shared references can be stored in a Canvas and
// updated by the application while still being drawn by the container. We
// delegate every method back to the inner object.
impl<T: Widget> Widget for std::rc::Rc<std::cell::RefCell<T>> {
    fn collect(&self, cmds: &mut Vec<RenderCommand>) {
        self.borrow().collect(cmds);
    }
    fn hit(&self, mx: f64, my: f64) -> bool {
        self.borrow().hit(mx, my)
    }
    fn mouse_input(&mut self, mx: f64, my: f64, pressed: bool) {
        self.borrow_mut().mouse_input(mx, my, pressed);
    }
    fn mouse_move(&mut self, mx: f64, my: f64) {
        self.borrow_mut().mouse_move(mx, my);
    }
    fn keyboard_input(&mut self, text: Option<&str>, key: Option<GuiKey>, pressed: bool) {
        self.borrow_mut().keyboard_input(text, key, pressed);
    }
    fn bounding_rect(&self) -> Option<[f32; 4]> {
        self.borrow().bounding_rect()
    }
    fn tooltip(&self) -> Option<&str> {
        // We can't return a reference into the RefCell borrow here, so we
        // intentionally return None; callers that need the tooltip of a
        // shared widget should access it through the inner borrow directly.
        None
    }
    fn apply_constraint(&mut self, container_w: f32, container_h: f32) {
        self.borrow_mut().apply_constraint(container_w, container_h);
    }
    fn shift(&mut self, dx: f32, dy: f32) {
        self.borrow_mut().shift(dx, dy);
    }
    fn apply_constraint_with(&mut self, c: &Constraint, cw: f32, ch: f32) {
        self.borrow_mut().apply_constraint_with(c, cw, ch);
    }
}
